[client]
remote_addr = "127.0.0.1:2333"
default_token = "123"

[client.transport]
type = "websocket"
[client.transport.websocket]
tls = false
path = "/rathole"

[client.services.foo1]
local_addr = "127.0.0.1:80"
